language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
- npm run build
notifications:
  email: false
  slack:
    secure: gabJFxp2eCYVKNUFNCyBSWF88CDx7Paec2ujs4el2Fb7CatSL9rmfhhQpBtTzz/BFHCgIYVBy/4aFwfqFIRmQlxIrRe4jaz5YvNtVc5GK3tOq2GFyKMLdVqUeyX1t1ZNXr99CpXi1SYujxtGhVzDAcM9xDYOmsFytZH/n++mSmGYIo1nXjko6KHWqPi7OGJlpaLgEQM9N9C0LMsGUaH/zysLHNtx3pooPqGg2gRl2LIOdTDwVWb6oBvs4c0nps9gTGWbYX0T477mQQvMKVmUYiZXijPSF7IUspmVOF1erZO8CCuRq4BeqmagjrgcRd2FFpy4QhOnKkHamMY31+aBviAzV8RdfDn4I16dJS3x+kLX+mLn10mOaMEF8bnQe/MfGYI9n+kalwx7iEfEjI5Aoj77dYLYma0PjYHRE3TJZkEJWc0Oy+q2hudZ2CAuNvu7jO9RrVfb5gmY+9MD10M4k+uXfqVplF0pJGKF2lrAmbDx5mtAMO2ZhsiGRilCEqH7VCe7PjZDKXQVqe1vfmscES3BwVfZJJIDTKuCps+aKKlHzN1h9rQ5josKpfWxWzSmkteERExyFBIr6ivFA3BkDIAxx5mJ2JVsO8VYpa5zmN4rtgVOVUaFYHwmXZhWbDZx+1L35rcMgKdtfYw6/Kw8nU2kBaMLZc//kc173HR2Kgs=
deploy:
  provider: npm
  email: deptno@gmail.com
  api_key:
    secure: gm/foFRhQZGV2OYMwaw9fELcFjha3ZVWpyXHb2XzlyR9ob1I+qRv31ZODpw6Tr5bB7DOPd5d9NGNuNgsWKZHrsx8f5Rw4mu+b2fsds0J3QfRrUgWnlvFdNdBHDwjcrINs6sAYtX9jEMxmnQ7SA1+dP/mqHHMmwKgTTfBg34oxwuX8khv8DFM6mxw1JD8vmQ2R49czlqe2KI/7B7Ln1IdUJAob5Ut9105CNvosccKPE1KtHrXqQn3v3Qgu/2epdqCbw/yCxiAPBUiNPRUTmwKDxSLT75dDp368hCZh0o4J3r7u5nq10uel5WhzI5ItPrSkq/xM8F2leBnX41w8yZLBfKwXm9DAtImcWjukLOk/y+11BTcld4MopsnqpnERAxrdBcpo2SaiZoHhhj+TXLMrK34mNSSH+52J3taLmfdhi3ZYrUxgAF1AmD6awmNwOHzAIQPZY/bLpB8cNMAt0Z3yLZ3UyF/pXYd2l10xSESvmfOGAZC5TxpINkba2jtrJv06H4ai15fBDGK76+FquCojr0VtHxTCj5z0e5eph3SPsLGLXUtjGcZIRB0QUvLDPMjU8OvQb+eoMMc8Uar7GELPgyz4s8ZrrQbdr66qc7+RR3r8GtpclWo6Ju97uAosUpMWKvvJd+nKdI+7uiqsOHDNIYAf+Ari1154rOx9Pf016E=
  on:
    tags: true
    repo: deptno/render-worker-pool-manager
