language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install:
- npm install
- npm run build
notifications:
  email: false
  slack:
    secure: gabJFxp2eCYVKNUFNCyBSWF88CDx7Paec2ujs4el2Fb7CatSL9rmfhhQpBtTzz/BFHCgIYVBy/4aFwfqFIRmQlxIrRe4jaz5YvNtVc5GK3tOq2GFyKMLdVqUeyX1t1ZNXr99CpXi1SYujxtGhVzDAcM9xDYOmsFytZH/n++mSmGYIo1nXjko6KHWqPi7OGJlpaLgEQM9N9C0LMsGUaH/zysLHNtx3pooPqGg2gRl2LIOdTDwVWb6oBvs4c0nps9gTGWbYX0T477mQQvMKVmUYiZXijPSF7IUspmVOF1erZO8CCuRq4BeqmagjrgcRd2FFpy4QhOnKkHamMY31+aBviAzV8RdfDn4I16dJS3x+kLX+mLn10mOaMEF8bnQe/MfGYI9n+kalwx7iEfEjI5Aoj77dYLYma0PjYHRE3TJZkEJWc0Oy+q2hudZ2CAuNvu7jO9RrVfb5gmY+9MD10M4k+uXfqVplF0pJGKF2lrAmbDx5mtAMO2ZhsiGRilCEqH7VCe7PjZDKXQVqe1vfmscES3BwVfZJJIDTKuCps+aKKlHzN1h9rQ5josKpfWxWzSmkteERExyFBIr6ivFA3BkDIAxx5mJ2JVsO8VYpa5zmN4rtgVOVUaFYHwmXZhWbDZx+1L35rcMgKdtfYw6/Kw8nU2kBaMLZc//kc173HR2Kgs=
deploy:
  provider: npm
  email: deptno@gmail.com
  api_key:
    secure: HW/9KV8zzsTdIRscpfTXPHvfXV54Y5Wuc4kuvlY9icNKCcwVo7pMJ1ImOgL+KdKmJ8JHN9nKf/GcGFZhQ9Rx7FC0iDeZDpGjxZKG1qyiTkiSbvhY/+2I1dhZ3l9wgpSiTasw/w+e07Umkjk40zPqDH1V2NNriqDsDlNNdMeLDq+Reb9AzGPoUGVRzRWNKfqofSuMGtcCA1x1th7RWhcMFeuvGxC+XwOl/D5pJa8hcaDBDUHZcrpsPEe6pTU3P+HUZwptl355X/YML/L/Bofefm0qevzTJG6CQs2U5t88qvNkoD9plANqauLUOw6WlInI9rix28ZhDSVEP2gdgTcJp270KQe0DOTgb2p7323k8PwiB+HkRDElSP8R1h1Oo4Xxh2w4xPxUDlDs32V0FUtXbrfGj7A4Be547I+XseT/a/G5lS21SheqTEtwHX26AQt5fid7ZAD0X7d8aMF4AvCkGfN92d/IOJxgk0yFlyMNngm3HAQDuBDo3hiDL+3CZ3LWahKCvXw/ihvh0QD8Orn3Z3ZJjExJdL7yJRrqfJUYXB8HsqslcnhPk975ISywTwwm0DSKCXbapveIyXj85MhlzPm1OJOif7GobnyXmVwkELU8kyQKrJTVlitR/Qk+8TB5V55iQnF0zSdFh8vW5NCjJxPdTYNkVSgO8alZcI3z/TU=
  on:
    tags: true
    repo: deptno/render-worker-pool-manager
